### ISSUE TITLE
No tests at all

### ISSUE THREAD

**Issue by kr1sp1n** [HGData/mk-node-hubspot#10]
Would be great to have at least some unit tests.

**Comment by brainflake** [comment]
100% agree! I initially developed this lib on a very tight schedule and regrettably never came back to flesh it out. But since it seems there's some interest from you and @tejasmanohar I think it'd be great to get it into better shape.

Want me to add you as a collaborator?

**Comment by kr1sp1n** [comment]
Thanks for your fast reply :smile: 
Yes, I would love to help you with the package; so please add me as a collaborator.

**Comment by tejasmanohar** [comment]
+100 for PRs adding unit tests. I'll make sure to review them :)

(can fork & send)

**Comment by brainflake** [comment]
Just added @kr1sp1n as a collaborator as well! Seems like the 3 of us have an interest in moving this forward and from what I've seen so far we're pretty much on the same page. It's probably still a good idea for us to branch & send PRs initially though so we're all aware and agree with what's going on.

**Comment by tejasmanohar** [comment]
:+1: sounds good to me.

and yes, I agree; let's branch and get at least one person to review before merging anything major

**Comment by brainflake** [comment]
Sounds great!

**Comment by kr1sp1n** [comment]
Would love to use jasmine as test framework.
Or do you have any other preferences?

**Comment by tejasmanohar** [comment]
I prefer Mocha or Tape. Jasmin. Coverage and maintenance on jasmine's node versions are meh + I prefer the design of the other two :)

**Comment by kr1sp1n** [comment]
No problem. Then it will be Mocha :coffee:

**Comment by tejasmanohar** [comment]
on a side note, let's make it a habit to most always push to npm after merging PR(s) (sets are fine) to master. if it's in-progress stuff, a non-master branch is best anyways :)

**Comment by brainflake** [comment]
Sounds good to me. Also +1 on mocha being a little better for node.

**Comment by brainflake** [comment]
I'll push the latest to npm. Going to bump to 0.2.0 due to removal of the extra statusCode property.

**Comment by fbritoferreira** [comment]
@brainflake We should use this to create a list of methods that don't have test so we can add them, like with the deals one. Also it may be good to separete them into their own files.

Here is a list so far that I have a look:
- [x] client.companies.getRecentlyCreated(opts,cb)
- [x] client.contacts.get(opts, cb)
- [x] client.contacts.getByEmail(email, cb)
- [x] client.contacts.getByEmailBatch(emails, cb)
- [x] client.contacts.getById(id, cb)
- [x] client.contacts.update(id, data, cb)
- [x] client.contacts.create(data, cb)
- [x] client.contacts.createOrUpdateBatch(data, cb)
- [x] client.deals.getRecentyModified(opts, cb)
- [x] client.deals.getRecentlyCreated(opts, cb)
- [x] client.deals.getById(id, cb)
- [x] client.deals.deleteById(id, cb)
- [x] client.deals.updateById(id, data, cb)
- [x] client.deals.create(data, cb)
- [x] client.deals.associate(id, objectType, associatedObjectId, cb)
- [x] client.deals.removeAssociation(id, objectType, associatedObjectId, cb)
- [x] client.pipelines.get(opts, cb)
- [x] client.lists.get(opts, cb)
- [x] client.lists.getOne(id, cb)
- [x] client.lists.getContacts(id, opts, cb)
- [x] client.lists.getRecentContacts(id, opts, cb)
- [x] client.lists.addContacts(id, contactBody, cb)
- [x] client.files.get(cb)
- [x] client.files.getOne(id, cb)
- [x] client.subscriptions.get(opts, cb)
- [x] client.campaigns.get(opts, cb)
- [x] client.campaigns.getOne(id, appId, cb)
- [x] client.campaigns.events(opts, cb)
- [x] client.broadcasts.get(opts, cb)

Lets  me know of what you think.

**Comment by brainflake** [comment]
Great idea @iTsFILIPOficial Looks like you got us pretty much up to speed.

**Comment by fbritoferreira** [comment]
@brainflake Do you have the travis ci/coverage results? The links in the Readme.md file are not working.

**Comment by fbritoferreira** [comment]
@brainflake I think we can go ahead and close this issues as most of the endpoints have test and just look at coverage reports to see which other endpoints don't have it.

**Comment by brainflake** [comment]
Agreed @iTsFILIPOficial Thanks for cranking out all of these tests
