### ISSUE TITLE
Documentation for owners.get not consistent with implementation

### ISSUE THREAD

**Issue by agrimm** [HGData/mk-node-hubspot#104]
Given the following code

    'use strict';

    const Hubspot = require('hubspot');
    const hubspot = new Hubspot({ apiKey: 'demo' });

    const opts = {};

    return hubspot.owners.get(opts)
    .then(results => {
      console.log("Successful get request of owners")
      console.log(results);
      return results;
    }).catch(err => {
      console.log("Failed get request of owners")
      console.log(err);
    });

I get the following error message:

    Failed get request of owners
    TypeError: cb is not a function
        at limiter.schedule.then.catch.err ((path omitted)/node_modules/hubspot/lib/client.js:120:13)
        at <anonymous>

This is because Owner.get currently only takes an argument of `cb`, rather than `opts, cb` as stated in the documentation, where it said `hubspot.owners.get(opts, cb)`

I haven't looked into whether the documentation should be changed to get rid of `opts`, or whether the implementation should be changed to utilize supplied options.

**Comment by MattMSumner** [comment]
Fixed by https://github.com/MadKudu/node-hubspot/pull/106

**Comment by adirzoari** [comment]
@MattMSumner @agrimm  how can I get owner by email?
i tried like
`hubspot.owners.get({email:'xxxxx@gmail.com'})`

but it's not working.
in docs, there is optional params of email
[https://developers.hubspot.com/docs/methods/owners/get_owners](https://developers.hubspot.com/docs/methods/owners/get_owners
)

**Comment by MattMSumner** [comment]
@adirzoari when I do the following with the demo account I get:
```js
const hubspot = new Hubspot({ apiKey: 'demo' })

hubspot.owners
  .get({ email: 'test_email56f09d1f9d20a@hubspot.com' })
  .then(data => {
    console.log(data)
  })
```

```
[ { portalId: 62515,
    ownerId: 9448208,
    type: 'PERSON',
    firstName: 'Testing',
    lastName: 'Owner',
    email: 'test_email56f09d1f9d20a@hubspot.com',
    createdAt: 1458609439699,
    updatedAt: 1458609439699,
    remoteList: [ [Object] ],
    hasContactsAccess: false } ]
```

Which version are you using?

**Comment by adirzoari** [comment]
last version
    "hubspot": "^1.3.4",

**Comment by adirzoari** [comment]
ok it's work. i insert invalid email.. thanks
is there any api to create user?

**Comment by MattMSumner** [comment]
By user do you mean owner? From https://developers.hubspot.com/docs/methods/owners/owners_overview

> The Owners API is read-only. Owners can only be created in Hubspot.
