### ISSUE TITLE
"remoteAssociation" there is no such a method. Do you mean "removeAssociation"?

### ISSUE THREAD

**Issue by umbrella-anton-kasian** [HGData/mk-node-hubspot#105]
https://github.com/brainflake/node-hubspot/blob/41699afcb18db4d8c60a00a4c68857a77c6445b3/lib/typescript/deal.ts#L37

**Comment by pcothenet** [comment]
Very likely, thanks for pointing it out.

**Comment by pcothenet** [comment]
Fixed typescript definition in release 1.3.3 (#112 )
