### ISSUE TITLE
decode error object

### ISSUE THREAD

**Issue by adirzoari** [HGData/mk-node-hubspot#149]
I'm trying to decode error object message

```
     async createContact(data) {
  
        try {
            let contact = await this.hubspot.contacts.create(data)
            return contact;
        }catch(e){
            debug('error object',e)
            throw new Error(e)
        }
      


   
}
```

I get this print in terminal
`
Error: StatusCodeError: 409 - {"status":"error","message":"Contact already exists","correlationId":"3c5db087-36d0-415c-94ef-039de03b848a","identityProfile":{"vid":2751,"identity":[{"value":"yamelzoari@gmail.com","type":"EMAIL","timestamp":1545572760708,"isPrimary":true},{"value":"a389c82e-60b3-4ef0-9c7c-4f19e432c0d3","type":"LEAD_GUID","timestamp":1545572760719}],"linkedVid":[],"isContact":true,"savedAtTimestamp":1545572760723},"error":"CONTACT_EXISTS","requestId":"71e6085bfec2c5d13046f6b344beed0e"}
`
but when I can't print the error message, it's not object.

**Comment by pcothenet** [comment]
@adirzoari I don't fully understand your problem, what do you mean by "when I can't print the error message, it's not object."?

**Comment by vkhomiv-hubspot** [comment]
Hi @adirzoari, is this issue still relevant? 
I'm going to close it if there no additional information.
