### ISSUE TITLE
'clientId' does not exist in type 'ApiOptions | AccessTokenOptions'.

### ISSUE THREAD

**Issue by aminnairi** [HGData/mk-node-hubspot#159]
**This bug is about** the `new Hubspot` constructor's signature being incorrect according to the TypeScript engine when taking an example from the documentation.

**The steps to reproduce the bug are:**
1. Create a folder named `node-hubspot-issue`
2. Open a terminal inside this folder and install the `typescript` & `ts-node` packages.

```console
$ yarn add --dev typescript ts-node
```

3. Install the `node-hubspot` package as well.

```console
$ yarn add --dev node-hubspot
```

4. Copy/paste the following content to a file named `index.ts` at the root of the `node-hubspot-issue` folder.

```typescript
import Hubspot from 'hubspot';

const hubspot = new Hubspot({
  clientId: '...',
  clientSecret: '...',
  redirectUri: '...',
  refreshToken: '...'
});
```

5. Inside the opened terminal, run the script.

```console
$ yarn ts-node index.ts
```
6. Observe the exception thrown in the terminal.

**The expected behavior was** to not have any errors thrown when using the constructor's signature from the documentation.

**Here are some screenshots.**
![image](https://user-images.githubusercontent.com/18418459/53411303-6d34de80-39c6-11e9-8964-3fb0fc0903c3.png)
![image](https://user-images.githubusercontent.com/18418459/53411339-8047ae80-39c6-11e9-9f83-2a139b772da1.png)

**Environment:**
 - ArchLinux: 241.7-2-arch
 - Docker: 18.09.2-ce, build 62479626f2
 - TypeScript: 3.3.3333
 - TS Node: 8.0.2
 - Hubspot: 2.1.1

**Comment by vkhomiv-hubspot** [comment]
Hi @aminnairi, a great explanation will check it soon

**Comment by vkhomiv-hubspot** [comment]
Verified - currently, it is fixed
