### ISSUE TITLE
Unexpected Token ...

### ISSUE THREAD

**Issue by swoopapp** [HGData/mk-node-hubspot#161]
https://github.com/MadKudu/node-hubspot/blob/master/lib/oauth.js line 12

I seemed to have "Fixed" the error by deleting all the ...data spread from this page.

Can someone provide input on what this will do?

Thanks!

**Comment by MattMSumner** [comment]
This is the spread operator: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals

This is basically adding the properties on data to the params object:

```
    {
      client_id: this.client.clientId,
      redirect_uri: this.client.redirectUri,
      ...data,
    }
```
In the above snippit, if data = `{some_prop: some_value }` then the result would be:
```
    {
      client_id: this.client.clientId,
      redirect_uri: this.client.redirectUri,
      some_prop: some_value,
    }
```

But if data has a `client_id` or `redirect_uri` they will get overridden i.e. `data = {client_id: new_id, some_prop: some_value}`:

```
    {
      client_id: new_id,
      redirect_uri: this.client.redirectUri,
      some_prop: some_value,
    }
```

**Comment by pcothenet** [comment]
Yeah, so the spread operator (`...`) is only supported by node versions >= 8.

(@MattMSumner we didn't totally pay attention to version support when we did this part)

A proposition to fix is #156 (move to typescript and add babel).

@swoopapp which version of node are you using? Is updating to a more recent version of node on your side an option?

**Comment by swoopapp** [comment]
thanks @MattMSumner and thanks @pcothenet for the quick responses! I am currently running node v6, hence the reason it bugged out. The temporary fix was to delete it from my package, or I could upgrade to node v8?

**Comment by pcothenet** [comment]
If you get to a node > 8, that error should definitely go away.

**Comment by vkhomiv-hubspot** [comment]
Now we have minimal node version requirement set to `"node": ">=10.0.0"`.
