### ISSUE TITLE
Contacts getById should accept optional parameters

### ISSUE THREAD

**Issue by shhac** [HGData/mk-node-hubspot#162]
`contacts.getById` only takes `id`, but per Hub Spot spec there are more options that can go into the URL query string (as it is a GET)

https://developers.hubspot.com/docs/methods/contacts/get_contact

```js
string[]? property
string? propertyMode // "value_only", "value_and_history"
string? formSubmissionMode // "all", "none", "newest", "oldest"
boolean? showListMemberships
```

Solution:

Add an `options` param which accepts these values and adds them to `qs`

---

The signature is slightly different to the equivalent company/deal versions documented

* [get company](https://developers.hubspot.com/docs/methods/companies/get_company) has no params
* [get deal](https://developers.hubspot.com/docs/methods/deals/get_deal) has optional `includePropertyVersions` param

**Comment by pcothenet** [comment]
@shhac I'm short on time these days. Do you want to submit a PR? (looks like you've already researched this issue quite a bit)

**Comment by slouis** [comment]
I also need it, can you accept the PR soon ?
