### ISSUE TITLE
createEventType needs UserId

### ISSUE THREAD

**Issue by Creiger** [HGData/mk-node-hubspot#164]
When i use this method i got an error: "UserId not provided in request". I can see that some other methods use it, but not this one.

**Comment by vkhomiv-hubspot** [comment]
Hi @Creiger, could you please provide additional information according to this issue.  
https://github.com/MadKudu/node-hubspot/blob/511bbf5cc9f5745af061c06f6295189cedbf6297/lib/timeline.js#L8

`userId` is the required field and seems that used correctly
https://developers.hubspot.com/docs/methods/timeline/create-event-type
