### ISSUE TITLE
Expose `request` method publically

### ISSUE THREAD

**Issue by dobesv** [HGData/mk-node-hubspot#168]
When an API is not "wrapped" with a specific call in this package, it can still be handy to use the request wrapper you have created, currently called `_request` to make the request.  This benefits from the bottleneck throttling and request parsing and formatting.  

For example, the "batch association" endpoint doesn't have a wrapper defined in this package, but I can still call it like this:

```
(hubspot as any)
          ._request({
            method: 'PUT',
            path: '/crm-associations/v1/associations/create-batch',
            body: batch,
          })
```

It would be nice if this method were part of the public API and declared in the typescript definitions.

**Comment by pcothenet** [comment]
@dobesv this is a great idea!

**Comment by pcothenet** [comment]
@dobesv this is doable today with `_request` today, correct?. Are you recommending we rename it as `request`?

**Comment by dobesv** [comment]
@pcothenet I guess my idea was to:

1. Add it to the documentation
2. Add it to the typescript definitions

It might make sense to rename it as well, if the reason for the leading underscore is to indicate that it's "private".  The underscore could also be interpreted to mean you don't want it to conflict with some other naming convention from HubSpot, though.  I'm not personally concerned about that part.
