### ISSUE TITLE
Add workflow routes to documentation

### ISSUE THREAD

**Issue by joseph-mcallister** [HGData/mk-node-hubspot#171]
Really appreciate this wrapper! Since workflows are implemented, would suggest adding the routes to the documentation. Had to dig through the code to find what I need. 

Happy to put up a PR for docs if you'd like!

**Comment by iamEAP** [comment]
I'd also add that it'd be great when getting this wrapped up to also include this in the typescript hints.

I'll open up a PR handling docs and typescript shortly.
