### ISSUE TITLE
Add wrapper for update an existing contact by email

### ISSUE THREAD

**Issue by darudude** [HGData/mk-node-hubspot#174]
I noticed that the library is missing the ability to update a contact via email: https://developers.hubspot.com/docs/methods/contacts/update_contact-by-email

Right now the two options using the library are:
1)getByEmailand then an update
2)createOrUpdate

They both have drawbacks: 
1) the former requires 2 API calls
2) the latter doesn't satisfy use cases where you just want to try and update but don't want to create if not possible.

**Comment by joseph-mcallister** [comment]
This just isn't in the docs for some reason, but is actually in the package. This is the case for quite a few other hubspot supported API calls: https://github.com/MadKudu/node-hubspot/blob/4481221835b01140b12aa7df4327c5480b2fd9b1/lib/contact.js#L83

**Comment by vkhomiv-hubspot** [comment]
Hi @joseph-mcallister, thanks for reporting that. Could you please add issues if you see similar things, mush appreciate that. It will help fill the gaps quickly.
