### ISSUE TITLE
Can't set limiter in Typescript

### ISSUE THREAD

**Issue by paulinetheitgirl** [HGData/mk-node-hubspot#177]
When using typed Hubspot and doing:
```
new Hubspot({
    baseUrl: Config.hubspotUrl,
    apiKey: Config.hubspotApiKey,
    limiter: {
        maxConcurrent: 2,
        minTime: 1000 / 9,
      }
})
```
I get this error:
`Argument of type '{ baseUrl: string; apiKey: string; limiter: any; }' is not assignable to parameter of type 'ApiOptions | AccessTokenOptions'.
  Object literal may only specify known properties, and 'limiter' does not exist in type 'ApiOptions | AccessTokenOptions'.`

Do i need to install additional packages?

**Comment by pcothenet** [comment]
@paulinetheitgirl this seems to be an issue with the option type which does not include the limiter.

**Comment by pcothenet** [comment]
@paulinetheitgirl actually, this should be the fixed in the latest published version, can you checl

**Comment by paulinetheitgirl** [comment]
Works now, thanks!
