### ISSUE TITLE
Create or Update for Company

### ISSUE THREAD

**Issue by bhubbard** [HGData/mk-node-hubspot#194]
Create or Update for Company would be very useful!

**Comment by pcothenet** [comment]
Hi @bhubbard do you mean a single method to "upsert" a company?

**Comment by bhubbard** [comment]
Yes, I know the api doesn't have an exact endpoint for it, so 2 calls would be needed, but it would be very useful.

**Comment by antoine-pous** [comment]
i think this should be your own interface, the lib must reflect the HubSpot API, nothing more

**Comment by vkhomiv-hubspot** [comment]
Companies created through API will not be deduplicated by the Company domain name property.
It means that it is possible to create two companies with similar  `name`, `domain` etc.

If a company created via portal UI HubSpot will check for duplicates taking into account the `domain` field.

We can let the user pass the property they want to use for identifying uniqueness leaving it blank means no deduping

**Comment by vkhomiv-hubspot** [comment]
can't really do this - search will return multiple companies and we will not know which one to update. Also, Search is an expensive API call
