### ISSUE TITLE
Project config files inconsistency 

### ISSUE THREAD

**Issue by vkhomiv-hubspot** [HGData/mk-node-hubspot#199]
Config file for dev editors `.editorconfig` set end-of-line symbol to be `Unix-style`
 ```end_of_line = lf```

Config file for code prettying `.prettierrc` set end-of-line symbol to be `Windows-style`
```"endOfLine": "crlf"```

As I see it now part of files, mostly from the root folder (mostly configurations), has an end-of-line symbol set to `LF`, all other files (from lib and test folders) has `CRLF` symbol.  My IDE starts to freak out with it. 

Let's consider one common approach and update configuration files to use one only style. And I propose to extend `.eslintrc.js` file with more specific rules for the code structure, I can prepare PR with it.

**Comment by pcothenet** [comment]
Ahh, that's what was happening. I had the same freakout issues and couldn't figure it out.

Absolutely, all in for standardizing!
