### ISSUE TITLE
Add multiple properties for get all contacts

### ISSUE THREAD

**Issue by ckim06** [HGData/mk-node-hubspot#210]
From hubspots API documentation, the property field can be added multiple times, however, we cannot do this in a JSON object.  
For example, if I want firstname, email, and state, in the url I would have
property=firstname&property=email&property=state

**Comment by dylanjmcdonald** [comment]
You can pass in an array of strings into `property`.

**Example:**
```
hubspot.contacts.get({
  property: ['firstname', 'lastname', 'email']
})
.then((results) => {
  console.log(results);
})
.catch((err) => {
  console.error(err);
});
```

**Comment by ChristianClassen** [comment]
I've got a HubSpot newbie question:
How do I get back all properties for each contact?

Background: I want to query all my contacts and write all their information in a file (JSON) to export everything.

How would you do that?

**Comment by vkhomiv-hubspot** [comment]
Please check the samples repo https://github.com/HubSpot/integration-examples-nodejs
it contains such functionality to make an export to CSV file.
https://github.com/HubSpot/integration-examples-nodejs/blob/1578c8a0d73c5a3b18b98997f8a70cecc8bdf50f/contacts-app/index.js#L408
