### ISSUE TITLE
API support

### ISSUE THREAD

**Issue by RanNir143** [HGData/mk-node-hubspot#255]
Hey i am using this library to write an integration with hubspot, it works great but whenever i fetch deals using client.deals.getById(dealId) the strings of values inside the json are all words connected into one string.
for example the "deal type" property arrives like this {dealtype":{"value":"newbusiness","timestamp":1580907472738,"source":"CRM_UI","sourceId":"1344"}}
but the string value of the deal type was "New Business"
![image](https://user-images.githubusercontent.com/50296344/73921810-bbd64280-48d0-11ea-9f3a-b8eba737128b.png)
this also applies to "Deal Stage" property
any insights on how to resolve this? 
or is this is the response received from their api without normalization on this librarys' end?

**Comment by vkhomiv-hubspot** [comment]
Hi ranyo2, 

yes, that's the way how HubSpot keeps the property identifiers.  The library itself just wraps the API - that's the original response.

So I would suggest to use `hubspot.deals.properties.getByName(name)` to get additional info about specific property. Or make one request and receive all the properties with all additional information `hubspot.deals.properties.get()`

Cheers!
