### ISSUE TITLE
Version Bump/Release Cadence

### ISSUE THREAD

**Issue by dompenn2010** [HGData/mk-node-hubspot#275]
Hey folks, 

I've contributed to very few open source projects in my time so I'm hoping someone can help me understand how this works!

I need the Ticket API which seems to have been merged **after** 2.3.10. 

How is the release cycle determined? Is it solely a version bump PR? In which case is that something **anyone** can submit? 

If this is a standard practice I can read about elsewhere please point me in the right direction.

Thanks for the help!

**Comment by vkhomiv-hubspot** [comment]
Hey @dompenn2010, I'll make a release soon, stay curious!

**Comment by vkhomiv-hubspot** [comment]
@davehenton  Ticket API released with the 2.3.11 version

**Comment by dompenn2010** [comment]
> Hey @dompenn2010, I'll make a release soon, stay curious!

Thanks @vkhomiv-hubspot, love the swift response!
