### ISSUE TITLE
[Urgent] CMS File API is deprecated

### ISSUE THREAD

**Issue by sanychernizon** [HGData/mk-node-hubspot#297]
**v2 is not working anymore.** See the doc fot the new endpoint: https://legacydocs.hubspot.com/docs/methods/files/v3/upload_new_file

**Comment by ksvirkou-hubspot** [comment]
Hi @sanychernizon 
check this method please
 https://github.com/MadKudu/node-hubspot/blob/master/lib/file.js#L108
 
 it is  v2.3.14

**Comment by sanychernizon** [comment]
Thanks @ksvirkou-hubspot :) 
Im using this method and works fine until yesterday..

Im start a receiving this error: `FetchError: invalid json response body at https://api.hubapi.com/filemanager/api/v2/files?overwrite=false&hidden=true&hapikey=XXXX-XXXX reason: Unexpected token < in JSON at position 0\n` ...

I dont change anything... any idea?

**Comment by sanychernizon** [comment]
forget, i was using the hubspot **v2.3.13**
Now is working fine :)
