### ISSUE TITLE
ReferenceError in client.js

### ISSUE THREAD

**Issue by synhershko** [HGData/mk-node-hubspot#32]
https://github.com/brainflake/node-hubspot/blob/d99b4c0f6871c7f484ef7ae8bfa2d9cc6dbc9b4a/lib/client.js#L24 cb is not defined here

Running a method without setting a key first will result in the following error

```
.../node_modules/hubspot/lib/client.js:24
      return cb(new Error("You must provide a key."));
             ^

ReferenceError: cb is not defined
    at Object.useKey (.../node_modules/hubspot/lib/client.js:24:14)
```

**Comment by brainflake** [comment]
Apologies, I just saw this. This is fixed.
