### ISSUE TITLE
vulnerability in request

### ISSUE THREAD

**Issue by sanpoChew** [HGData/mk-node-hubspot#36]
Hey guys, any chance of a bump on the version number of request (>=v2.74.0)? Current one you are using is insecure:

https://nodesecurity.io/check/hubspot

Great tool by the way!

**Comment by fbritoferreira** [comment]
@sanpoChew I have created a pull request for this already thank you for pointing it out. Follow #37 for any other discussion

**Comment by brainflake** [comment]
Thanks @sanpoChew @iTsFILIPOficial 

We'll get the version bumped
