### ISSUE TITLE
Better management of api limit

### ISSUE THREAD

**Issue by pcothenet** [HGData/mk-node-hubspot#51]
Added a support for checking API limits:

But couple issues:

- should probably be optional (makes a couple extra api calls + complicate the code)
- doesn't seem to work with all scopes on OAuth (at least not with the ones I have)

Will try to do a cleaner implementation soon.

**Comment by brainflake** [comment]
It looks like setting `maxUsePercent` to 0 makes it optional, no?

**Comment by pcothenet** [comment]
Yeah, but it's a little bit awkward and the documentation lacks a bit.

**Comment by ddoan** [comment]
There's also a bug:

```
diff --git a/lib/client.js b/lib/client.js
index 0b7f1b7..4ea6140 100644
--- a/lib/client.js
+++ b/lib/client.js
@@ -156,7 +156,7 @@ class Client extends EventEmitter {
       method: 'GET',
       path: '/integrations/v1/limit/daily'
     }).then(results => {
-      this.limit = results[0]
+      this.limit = _.find(results, {'name': 'api-calls-daily'})
       return this.limit
     })
   }
```

Because Hubspot decided to put their Sales Pro license information in this API:

```
[
  {
    "name": "sales-pro-seats",
    "usageLimit": ...,
    "currentUsage": ...,
    "collectedAt": 1510262521682,
    "fetchStatus": "SUCCESS",
    "resetsAt": null
  },
  {
    "name": "api-calls-daily",
    "usageLimit": 40000,
    "currentUsage": 26,
    "collectedAt": 1510262521686,
    "fetchStatus": "SUCCESS",
    "resetsAt": 1510300800000
  }
]
```

**Comment by pcothenet** [comment]
@ddoan is it related to #66 ?

**Comment by alexatdivvy** [comment]
Also, just to chime in, there are some functions like `deals.getById` that don't allow options to be passed.

**Comment by pcothenet** [comment]
@alexatdivvy thanks for reporting. That seems to be a different problem, do you mind opening a new issue (PRs welcome too!)

**Comment by alexatdivvy** [comment]
Yeah - totally. Just figured it was semi-relevant, since you can't pass `maxUsePercent=0` to those functions.

**Comment by ddoan** [comment]
@pcothenet yes, same issue thanks!
