### ISSUE TITLE
API get pages

### ISSUE THREAD

**Issue by amit777** [HGData/mk-node-hubspot#52]
I wanted to migrate to this node module from https://github.com/Datahero/node-hubspot

In the other module I am able to do something like:

api.get_pages({is_draft: false}.. )

Is there an equivalent method in this module?

**Comment by amit777** [comment]
it looks like the content object is not there.  I will fork and create a pull request today.  Thanks for this awesome module!

**Comment by pcothenet** [comment]
Awesome!

**Comment by MattMSumner** [comment]
@amit777 looks like the three endpoints you were hoping to get added were `owners/v2/owners`, `deals/v1/deal/recent/created`, `deals/v1/properties`, `companies/v2/companies/recent/created`. The only endpoint we don't have support for yet is `deals/v1/properties`. I'm going to close this issue for now but feel free to reopen if that last endpoint is still one you're hoping gets added.
