### ISSUE TITLE
Plans to add workflows?

### ISSUE THREAD

**Issue by hiddenkirby** [HGData/mk-node-hubspot#54]
Hi there,
   Was wondering if you had plans to add workflows to the lib.

**Comment by pcothenet** [comment]
Hi @hiddenkirby, no immediate plan at the moment, but PRs are very welcome. It should be relatively easy to add by following the current model.

In case anyone here has some time to contribute, are there any API endpoints (from the [docs](https://developers.hubspot.com/docs/methods/workflows/v3/get_workflows) that are more important to you than others?

**Comment by hiddenkirby** [comment]
Roger that. I'll see what i have time for :).  I'm in a rush for a deliverable so i resorted to using request lib for the api calls.  Maybe over the weekend i can come back for a PR.

**Comment by MattMSumner** [comment]
Looks like a workflows PR got merged. @pcothenet is this issue good to close?

**Comment by MattMSumner** [comment]
Closing for now. Feel free to reopen if these still need to be added.
