### ISSUE TITLE
api callback called twice on error

### ISSUE THREAD

**Issue by jaredatron** [HGData/mk-node-hubspot#58]
I dont think you want to throw in your promise https://github.com/brainflake/node-hubspot/blob/master/lib/client.js#L110 since it will cause the catch below to call the callback with the error twice.

**Comment by vkhomiv-hubspot** [comment]
Hi @deadlyicon, it seems like things changed a little from the time of your last comment could you please check if the issue is still relevant. If so please add additional details. 
Thanks a lot!
