### ISSUE TITLE
best way to handle paged results

### ISSUE THREAD

**Issue by amit777** [HGData/mk-node-hubspot#59]
when doing a query against the contacts api or any other api that can returned paged results, is there a built in method to get all the results?  Or do we need to create our own iterator to do it?  A quick example in the README.md would be awesome!

**Comment by pcothenet** [comment]
Hi Amit,

Nothing built-in the app but I can share a quick example of iterator (probably this weekend)

**Comment by nhim175** [comment]
@pcothenet Looking forward to your example!

**Comment by et** [comment]
@amit777 - Not sure if you still need it, but this is the code I'm using (minus some typescript). I'm still playing with how I want it (since sometimes I want extra properties), but this should get you going.

```js
  async getAll({ contacts = [], offset = 0 } {
    const count = 100;

    const response = await this.hubspot.contacts.get({
      count,
      vidOffset: offset
    });

    contacts = contacts.concat(response.contacts);

    if (response['has-more'] === false) {
      return contacts;
    } else {
      return this.getAll({ properties, contacts, offset: response['vid-offset']});
    }
  }
```

And you can call it as:

```js
const contacts = await getAll();
```

I'll eventually open a PR to get this built in once I'm comfortable with the results.

**Comment by pcothenet** [comment]
On our end, we handle it with a stream to (supposedly) manage memory better.

**Comment by et** [comment]
Ah yeah that makes sense. I just started using hubspot so I have very little data at the moment.

**Comment by MattMSumner** [comment]
@et did you ever end up with an example you'd be comfortable adding to the readme?

@pcothenet do you have an example of how you're handling this with a steam?

**Comment by et** [comment]
@MattMSumner - my apologies but that was for a former client that I no longer work with. I will say that I think @pcothenet's approach is better for larger data sets.

**Comment by mritzco** [comment]
Hi,

After testing several versions some uglier than others, I found a generator function to be the best option. 

Check out this page: https://javascript.info/async-iterators-generators

Usually, I just wanted to get all the results to do some individual processing without worrying about the data loading. 

The following code will make the loop behave like a local collection. Every time you call it, it will return the next record of the loaded paged results, and will load the next page when it doesn't have any records left to return. 

The loop is controlled by the params.count variable. When set to 0 it will stop. The parameters function is a parameter itself but defaults to the *parameters* function I added under.

Generic *every* generator to use with all paginated API's
```js
async function* every(fnRequest, fnParams) {
  if (!fnParams) fnParams = parameters;
  let params = fnParams(0, 1, 1);
  while (params.count !== 0) {
    let data = await fnRequest(params);

    for (let entry of data.results) {
      yield entry;
    }
    params = fnParams(data.offset, data.total);
  }
}
```

This is more specific to the HubSpot API. It simply sets the offset and let you control when to stop the generator *every*. Other API's use skip or need extra values. 
```js
function parameters(offset, total, count = 20) {
  if (offset >= total) count = 0;
  return { count, offset };
}
```

Now you can use directly or wrap in a *getall* . 

```js
// let acc = [];
for await (const company of every(client.company.getRecentlyModified) {
    // Limit by some property, if you want to...
    if (company.properties.hs_lastmodifieddate.value < fromts) {
      break;
    }
   // Do whatever you want with company... 
   // You can loop over it like if it's a local collection.

  // If you only want to return them all:
  // acc.push(company);
}

```

Function around this loop has to be an **async**. You are able to make your *getall* wrapping function to use async, callbacks or promises,  run the full loop and return the *acc* array.
