### ISSUE TITLE
refreshToken example does not work

### ISSUE THREAD

**Issue by milesflo** [HGData/mk-node-hubspot#64]
```
const Hubspot = require('hubspot');
const hubspot = new Hubspot({
  clientId: process.env.HUBSPOT_CLIENT_ID,
  clientSecret: process.env.HUBSPOT_CLIENT_SECRET,
  redirectUri: `http://localhost:${PORT}`,
  refreshToken: "someStringHere"
})
return hubspot.refreshAccessToken()
  .then(results => {
    console.log(results.access_token)
    console.log(hubspot.accessToken) // this assigns the new accessToken to the client, so your client is ready to use
    return hubspot.contacts.get()
  })
  .catch((err)=> console.log(err))
```

This method does not work. I'm getting a `400 BAD_REFRESH_TOKEN` error message. 

I've diagnosed the problem as a poor refreshToken when instantiating the client which throws an error before I can get to the refreshToken() method.. I searched the website and forums for what should be in the refresh token property... can't find anything.

Anyone know where I can find what should go here?

**Comment by pcothenet** [comment]
Interesting.

I have the following code running in production (and I believe it's working)

```javascript
const params = {
  clientId: hubspot_app.clientId,
  clientSecret: hubspot_app.clientSecret,
  redirectUri: `${hubspot_app.redirectUri}?state=${tenant}`,
  refreshToken: refresh_token
}
const hubspot = new Hubspot(params)

if (refresh_token) {
  return hubspot.refreshAccessToken()
    .then(results => // save your new access token)
    .then(() => hubspot)
}
```

I don't quite have much time to look at the code today, maybe tomorrow.

**Comment by milesflo** [comment]
Where are you defining `refresh_token`?

**Comment by pcothenet** [comment]
Are you using `someStringHere` or are you using an actual `refreshToken`?

`refreshToken` is returned by the HubSpot API at the end of the OAuth flow. 
In this module, that's in the result of [getAccessToken](https://github.com/brainflake/node-hubspot/blob/master/lib/oauth.js#L18)

**Comment by milesflo** [comment]
I'm using someStringHere.

I'm having a chicken/egg situation. I can't get the refresh token without having a refresh token. Can I find one in the admin control panel of the app? I can't instantiate the class without it.

**Comment by milesflo** [comment]
I tracked down a HAPI key, though this doesn't appear to replace the refreshToken

**Comment by pcothenet** [comment]
If you have an hapi key, you can use directly, you don't need to bother with tokens.

Tokens are only used in an OAuth scenario where you're building an app that someone else will be using. They then give you access to their HubSpot instance via the OAuth flow: https://developers.hubspot.com/docs/methods/oauth2/oauth2-overview

If you have an `apiKey`, you should be able to instantiate your client with just
```
const hubspot = new Hubspot({ apiKey: 'abc' })
```

**Comment by milesflo** [comment]
Thanks for the quick response. I found that I was approaching this from the wrong direction... Going to mark this closed.
