### ISSUE TITLE
Plan for Form support

### ISSUE THREAD

**Issue by sammydeveille** [HGData/mk-node-hubspot#69]
Hi guys

Thanks for what is available so far. 
I was wondering wether you had in mind to support the Forms?

Cheers
Sam

**Comment by pcothenet** [comment]
Hi @sammydeveille no plan at the time but feel free to submit a Pull Request (should be fairly easy getting started by copying one of the existing methods)

**Comment by marleymarl** [comment]
I've added forms and will submit a pull request later today.

**Comment by LucasPaganini** [comment]
Any updates?
