### ISSUE TITLE
useKey function bug

### ISSUE THREAD

**Issue by swrocket** [HGData/mk-node-hubspot#71]
The useKey function requires a callback function for errors, but doesn't call it on success, which means that it can't be used properly.
```
function useKey (key, cb) {
    if (!key || typeof key !== 'string') {
      return cb(new Error("You must provide a key."));
    }

    self.key = key;
  }
```
It should probably be:
```
function useKey (key, cb) {
    if (!key || typeof key !== 'string') {
      return cb(new Error("You must provide a key."));
    }
    else {
        self.key = key;
        return cb(null);
    }
  }
```

**Comment by pcothenet** [comment]
Hi @swrocket which version are you using? I think I retired `useKey` in 1.0 (in favor of instantiating the apiKey via the constructor)

**Comment by swrocket** [comment]
Aha, yes, I'm on the previous version. Thanks for the reply.
