### ISSUE TITLE
Pass `properties` to query params for deals.getAssociated

### ISSUE THREAD

**Issue by nhim175** [HGData/mk-node-hubspot#75]
https://github.com/brainflake/node-hubspot/commit/f5187f85950c58acd751249fd4e34edd256ea3b5

Rest API supports passing multiple properties to query params, this is extra helpful when you want to see which pipeline and stage a deal belongs to. Otherwise you will need to send more API requests in order to get those properties.

**Comment by nhim175** [comment]
Actually added here: https://github.com/brainflake/node-hubspot/pull/74/commits/3663e50926696ff6e98a33ff7708adc46dca5eac

I will close this issue. Thanks!

**Comment by po5i** [comment]
Can you provide an example of use for multiple properties in a request?
