### ISSUE TITLE
feature request: timeline API

### ISSUE THREAD

**Issue by nhim175** [HGData/mk-node-hubspot#81]

**Comment by coderholic** [comment]
Any update on this? It'd be great to support it. Docs here: https://developers.hubspot.com/docs/methods/timeline/timeline-overview

**Comment by MattMSumner** [comment]
I'll close this once we get a release out. Hopefully early next week!

**Comment by MattMSumner** [comment]
Release is out! 1.3.2 continues the Timeline API.
