### ISSUE TITLE
feature request: workflows API

### ISSUE THREAD

**Issue by kenichi1985** [HGData/mk-node-hubspot#82]
Hi,

I'm working on a project require the workflows feature. Any chance that supports this feature in the future?

Thanks.
Luke

**Comment by iamEAP** [comment]
@kenichi1985 (and anyone else who finds themselves here in the future), I realize it's been over 1.5 years since you posted this, but this package does support workflows.

You can find the available methods here: https://github.com/MadKudu/node-hubspot/blob/master/lib/workflow.js

**Comment by vkhomiv-hubspot** [comment]
Thanks! @iamEAP
