### ISSUE TITLE
Use ResolveWithFullResponse for request-promise calls

### ISSUE THREAD

**Issue by darudude** [HGData/mk-node-hubspot#86]
Some of the HubSpot API Calls don't return any messages (like the update call - https://developers.hubspot.com/docs/methods/contacts/update_contact), and the status code needs to be validated to determine the success of the calls. Currently, the tests for node-hubspot wrapper validates the test as a success if the message returned is undefined, but that is not necessarily true. As per the HubSpot API documentation, all of the following cases will return an undefined message

- 204 when a contact is updated
- 401 when an unauthorized request is made, such as an expired access token of wrong API key.
- 404 when there is no existing contact with the specified vid.
- 500 when an internal server error occurs. Please alert us in the API Forum if you receive an HTTP 500 error.

**Comment by pcothenet** [comment]
Ah I see, good call.

The tricky thing will be to catch those errors without modifying the response format for existing calls (I'd prefer not introducing a breaking change). Maybe return the full response, parse and return the existing payload if good?

**Comment by darudude** [comment]
Or you could add the HTTP status code along with the response as a new key? You'd just have to document it

**Comment by pcothenet** [comment]
Good idea. Unfortunately, a couple of the calls are returning arrays or single records (without wrapper), so it seems wrong to add statusCode / statusMessage to the body without discrimination

**Comment by pcothenet** [comment]
Also, by default, [request-promise](https://github.com/request/request-promise) rejects the promise if the code is anything other than a 200:

>   By default, http response codes other than 2xx will cause the promise to be rejected

Are you sure about the behavior you're describing? See for example the tests I added in #91
