### ISSUE TITLE
cannot authenticate via oAUTH

### ISSUE THREAD

**Issue by JonRichter** [HGData/mk-node-hubspot#87]
not sure it is appropriate to ask a question here, but I have been struggling with initiating oAUTH with this Library. When I get authenticated I plan on adding timeline create functionality. I just have no idea what I am doing wrong. I used a sample app so I know I am on the right track with my variables. Here is my code, I desperately need a bump in the right direction. Maybe we could do a screen share and willing to pay as I have been battling this for 2 days. Guessing it is something simple I am missing.
I keep getting BAD_AUTH_CODE, "missing or unknown auth code". I could get data via APIkey but the timeline calls require oAUTH. My email is JonRichter@plainsmobile.com

const chai = require('chai')
const expect = chai.expect

const Hubspot = require('hubspot')

class hubspotapi {
	authorize(params) {
		return new Promise((resolve, reject) => {
			let body = '';
			if(params.client_id) {
				const pams = {
					code: 'codecodecode',
					clientId: 'xxxxx',
					clientSecret: 'yyyyyyy',
					redirectUri: 'https://plainsmobile.com'
					//
				}
				const hubspot = new Hubspot(pams)
				return hubspot.oauth.getAccessToken({
					pams // the code you received from the oauth flow
				}).then(data => {
					expect(res).to.have.a.property('access_token')
				})
				return hubspot.contacts.get().then(data => {
					expect(data).to.be.a('object')
					expect(data.contacts).to.be.a('array')
					expect(data.contacts[0]).to.be.an('object')
				})
				//return hubspot.refreshAccessToken()
				//  .then(results => {
  				//	console.log(results.access_token)
  				//	console.log(hubspot.accessToken) // this assigns the new accessToken to the client, so your client is ready to use
  				//	return hubspot.contacts.get()
				//  })
				
				resolve(response);
				
			} else {
				resolve();
			}
		});
	}
}
module.exports=hubspotapi;
[hubspotapi.txt](https://github.com/brainflake/node-hubspot/files/2014038/hubspotapi.txt)

**Comment by pcothenet** [comment]
Hi Jon,

For the `code` params, you're using the code passed back to you by the Hubspot callback?

Here's my code, hope that helps:

### Step 1: redirect from my app to Hubspot:

```javascript
const redirect_uri = `${get_redirect_uri(req)}?state=${state}`
const hubspot = new Hubspot({
  clientId: hubspot_app.clientId,
  redirectUri: redirect_uri
})
const authorization_url = hubspot.oauth.getAuthorizationUrl({ scope, optional_scope })
res.redirect(authorization_url)
```

### Step 2: Process the callback from Hubspot:

```javascript
const hubspot = new Hubspot({
    clientId: hubspot_app.clientId,
    clientSecret: hubspot_app.clientSecret,
    redirectUri: `${get_redirect_uri(req)}?state=${tenant}`
})

const code = req.query.code

try {
  const results = await hubspot.oauth.getAccessToken({ code })
} catch (e) {
  const { response = {} } = e
  const { body } = response
  const err = new Error(body.message)
  err.body = body
  err.status = results.status
  next(err)
}
```

**Comment by JonRichter** [comment]
thanks, could you send me your declarations (res)? I am having problems with res.redirect.
I think I can get this now,....

**Comment by JonRichter** [comment]
anyway I could get the files for the complete code for above? I really apologize I just can't put this all together, have been starting at this all week and can't get over the hump... I think I have the hubspot developer guides memorized but just can't piece this together for oAUTH... my apologies

**Comment by JonRichter** [comment]
resolved, just a number of things happening with hubspot api which makes it hard to use until you figure out how finicky it is....
