### ISSUE TITLE
Check API limit does not handle 10 requests / second limit

### ISSUE THREAD

**Issue by darudude** [HGData/mk-node-hubspot#89]
AS title suggests, if you're running a bunch of API calls, they'll start failing and you'll get the following error:

{“status”:“error”,“message”:“You have reached your secondly limit.”,“errorType”:“RATE_LIMIT”,“correlationId”:“6828d000-3d2f-4701-8d90-b21e53b0d005”,“policyName”:“SECONDLY”,“requestId”:“ce6a6a91-ac17-492f-bbdb-7d72477c319c”}

The API checker currently hits the APILimit end point, but that endpoint only handles the daily limit. 

Not sure the best way to handle it, but a quick fix might be to use the .delay chain function on the request-promise object

**Comment by AustinLeeGordon** [comment]
@pcothenet Can this be closed?

**Comment by pcothenet** [comment]
Closed by #154
